language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
before_install:
  - cd client
  - npm start
script:
  - npm run test:prod
  - npm run cypress:all
  - npm run build:prod
after_success:
  - npm run report-coverage
